version: 2

sources:
  - name: olist_raw
    database: module2-assignment-project
    schema: olist_raw2   # your raw dataset
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: geolocation
      - name: category_translation